import "dotenv/config";

async function main() {
  const { PrismaClient } = await import("../src/generated/prisma/client.js");
  const { PrismaPg } = await import("@prisma/adapter-pg");

  const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
  const prisma = new PrismaClient({ adapter });

  const courts = [
    {
      name: "Garden Halls Tennis",
      slug: "garden-halls",
      bookingSystem: "microsoft_bookings",
      bookingUrl: "https://outlook.office365.com/owa/calendar/GardenHallsTennis@upp-ltd.com/bookings/",
      location: "Garden Halls, Cartwright Gardens, London WC1H 9EN",
      metadata: {
        lat: 51.5268, lng: -0.1275,
        serviceTypes: [
          { name: "Garden Halls Resident", duration: "1 hour", price: "Free" },
          { name: "Student", duration: "1 hour", price: "£5/hr" },
          { name: "WC1 Resident", duration: "1 hour", price: "£5/hr" },
          { name: "Visitor", duration: "1 hour", price: "£10/hr" },
        ],
      },
    },
    {
      name: "Islington Tennis Centre",
      slug: "islington-tennis-centre",
      bookingSystem: "better",
      bookingUrl: "https://bookings.better.org.uk/location/islington-tennis-centre/tennis-activities",
      location: "Market Road, London N7 9PL",
      metadata: {
        lat: 51.5513, lng: -0.1152,
        activity: "tennis-court-outdoor",
        venue: "islington-tennis-centre",
        deepLink: "https://bookings.better.org.uk/location/islington-tennis-centre/tennis-court-outdoor",
        activities: ["tennis-court-outdoor", "tennis-court-indoor"],
      },
    },
    // ClubSpark courts
    {
      name: "Finsbury Park Tennis",
      slug: "finsbury-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/FinsburyPark/Booking/BookByDate",
      location: "Finsbury Park, London N4 2DE",
      metadata: {
        lat: 51.5637, lng: -0.1052,
        venue: "FinsburyPark",
        deepLink: "https://clubspark.lta.org.uk/FinsburyPark/Booking/BookByDate",
        courts: 8, surface: "Hard", floodlit: true,
        pricing: { offPeak: "£4", peak: "£7" },
      },
    },
    // Disabled: requires ClubSpark login
    {
      name: "Paddington Recreation Ground",
      slug: "paddington-recreation-ground",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/PaddingtonRecreationGround/Booking/BookByDate",
      location: "Randolph Avenue, London W9 1PD",
      enabled: false,
      metadata: {
        lat: 51.5281, lng: -0.1828,
        venue: "PaddingtonRecreationGround",
        deepLink: "https://clubspark.lta.org.uk/PaddingtonRecreationGround/Booking/BookByDate",
        courts: 13, surface: "Tarmac & Synthetic", floodlit: true,
        pricing: { nonMember: "£8-10/hr" },
        note: "Requires ClubSpark login — cannot scrape anonymously",
      },
    },
    // Disabled: requires ClubSpark login
    {
      name: "Rosemary Gardens Tennis",
      slug: "rosemary-gardens",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/RosemaryGardens/Booking/BookByDate",
      location: "Southgate Road, London N1 3JP",
      enabled: false,
      metadata: {
        lat: 51.5396, lng: -0.0876,
        venue: "RosemaryGardens",
        deepLink: "https://clubspark.lta.org.uk/RosemaryGardens/Booking/BookByDate",
        courts: 2, surface: "Tarmac",
        note: "Requires ClubSpark login — cannot scrape anonymously",
      },
    },
    {
      name: "Clissold Park Tennis",
      slug: "clissold-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/ClissoldParkHackney/Booking/BookByDate",
      location: "Clissold Park, London N16 0BF",
      metadata: {
        lat: 51.5612, lng: -0.0823,
        venue: "ClissoldParkHackney",
        deepLink: "https://clubspark.lta.org.uk/ClissoldParkHackney/Booking/BookByDate",
        courts: 7, floodlit: true,
        pricing: { offPeak: "£4-5" },
      },
    },
    {
      name: "Hackney Downs Park Tennis",
      slug: "hackney-downs",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/HackneyDowns/Booking/BookByDate",
      location: "Hackney Downs, London N16",
      metadata: {
        lat: 51.5545, lng: -0.0574,
        venue: "HackneyDowns",
        deepLink: "https://clubspark.lta.org.uk/HackneyDowns/Booking/BookByDate",
        courts: 5, floodlit: true,
        pricing: { offPeak: "£4-5" },
      },
    },
    {
      name: "London Fields Tennis",
      slug: "london-fields",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/LondonFieldsPark/Booking/BookByDate",
      location: "London Fields, London E8",
      metadata: {
        lat: 51.5413, lng: -0.0596,
        venue: "LondonFieldsPark",
        deepLink: "https://clubspark.lta.org.uk/LondonFieldsPark/Booking/BookByDate",
        courts: 2, surface: "Porous Macadam",
        pricing: { adult: "£4.50/hr" },
      },
    },
    {
      name: "Geraldine Mary Harmsworth Park Tennis",
      slug: "geraldine-mary-harmsworth",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/GeraldineMaryHarmsworth/Booking/BookByDate",
      location: "St George's Road, London SE1 6HZ",
      metadata: {
        lat: 51.4978, lng: -0.1026,
        venue: "GeraldineMaryHarmsworth",
        deepLink: "https://clubspark.lta.org.uk/GeraldineMaryHarmsworth/Booking/BookByDate",
        courts: 2, floodlit: true, surface: "All-weather",
      },
    },
    // Disabled: Tennis In Lambeth requires ClubSpark login
    {
      name: "Archbishop's Park Tennis",
      slug: "archbishops-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/TennisInLambeth/Booking/BookByDate",
      location: "Lambeth Palace Road, London SE1 7LQ",
      enabled: false,
      metadata: {
        lat: 51.4984, lng: -0.1149,
        venue: "TennisInLambeth",
        deepLink: "https://clubspark.lta.org.uk/TennisInLambeth/Booking/BookByDate",
        courts: 2, surface: "Tarmac",
        note: "Requires ClubSpark login — cannot scrape anonymously",
      },
    },
    // Disabled: Tennis In Lambeth requires ClubSpark login
    {
      name: "Kennington Park Tennis",
      slug: "kennington-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/TennisInLambeth/Booking/BookByDate",
      location: "Kennington Park Road, London SE11 4BE",
      enabled: false,
      metadata: {
        lat: 51.4856, lng: -0.1077,
        venue: "TennisInLambeth",
        deepLink: "https://clubspark.lta.org.uk/TennisInLambeth/Booking/BookByDate",
        courts: 4, surface: "Tarmac", floodlit: true,
        note: "Requires ClubSpark login — cannot scrape anonymously",
      },
    },
    {
      name: "Spring Hill Tennis",
      slug: "spring-hill",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/SpringHillParkTennis/Booking/BookByDate",
      location: "Spring Hill, Hackney, London",
      metadata: {
        lat: 51.5505, lng: -0.0530,
        venue: "SpringHillParkTennis",
        deepLink: "https://clubspark.lta.org.uk/SpringHillParkTennis/Booking/BookByDate",
        courts: 2, surface: "Tarmac",
        pricing: { adult: "£3.90/hr" },
      },
    },
    {
      name: "Elthorne Tennis Club",
      slug: "elthorne-tennis",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/ElthorneTennis/Booking/BookByDate",
      location: "Elthorne Park, Haringey, London",
      metadata: {
        lat: 51.5770, lng: -0.1289,
        venue: "ElthorneTennis",
        deepLink: "https://clubspark.lta.org.uk/ElthorneTennis/Booking/BookByDate",
        courts: 3, floodlit: true,
        pricing: { nonMember: "£8.70/hr", floodlit: "£11.70/hr" },
      },
    },
    // Millfields Park removed — ClubSpark URL returns 404
    {
      name: "Southwark Park Tennis",
      slug: "southwark-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/SouthwarkPark/Booking/BookByDate",
      location: "Jamaica Gate entrance, London SE16",
      metadata: {
        lat: 51.4929, lng: -0.0565,
        venue: "SouthwarkPark",
        deepLink: "https://clubspark.lta.org.uk/SouthwarkPark/Booking/BookByDate",
        courts: 4, surface: "Tarmac",
      },
    },
    {
      name: "Clapham Common Tennis",
      slug: "clapham-common",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/claphamcommon/Booking/BookByDate",
      location: "Windmill Drive, London SW4 9AN",
      metadata: {
        lat: 51.4600, lng: -0.1580,
        venue: "claphamcommon",
        deepLink: "https://clubspark.lta.org.uk/claphamcommon/Booking/BookByDate",
        courts: 8, floodlit: true,
      },
    },
    // Tower Hamlets courts (migrated from Courtside to ClubSpark)
    {
      name: "Bethnal Green Gardens Tennis",
      slug: "bethnal-green-gardens",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BethnalGreenGardens/Booking/BookByDate",
      location: "Malcolm Place, London E2 0EU",
      metadata: {
        lat: 51.5280, lng: -0.0625,
        venue: "BethnalGreenGardens",
        deepLink: "https://clubspark.lta.org.uk/BethnalGreenGardens/Booking/BookByDate",
        courts: 4, surface: "Hard", floodlit: true,
        pricing: { adult: "£4-6" },
      },
    },
    {
      name: "King Edward Memorial Park Tennis",
      slug: "king-edward-memorial",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/KingEdwardMemorialPark/Booking/BookByDate",
      location: "Glamis Road, London E1W 3TD",
      metadata: {
        lat: 51.5087, lng: -0.0467,
        venue: "KingEdwardMemorialPark",
        deepLink: "https://clubspark.lta.org.uk/KingEdwardMemorialPark/Booking/BookByDate",
        courts: 4, surface: "Porous Macadam",
        pricing: { adult: "£4-6" },
      },
    },
    // Disabled: requires ClubSpark login
    {
      name: "St John's Park Tennis",
      slug: "st-johns-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/StJohnsPark/Booking/BookByDate",
      location: "Plevna Street, Tower Hamlets, London",
      enabled: false,
      metadata: {
        lat: 51.5166, lng: -0.0270,
        venue: "StJohnsPark",
        deepLink: "https://clubspark.lta.org.uk/StJohnsPark/Booking/BookByDate",
        courts: 2, floodlit: true,
        pricing: { offPeak: "£4", peak: "£6" },
        note: "Requires ClubSpark login — cannot scrape anonymously",
      },
    },
    // Disabled: requires ClubSpark login (Better URL defunct)
    {
      name: "Highbury Fields Tennis",
      slug: "highbury-fields",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/HighburyFieldsLondon/Booking/BookByDate",
      location: "Highbury Fields, London N5",
      enabled: false,
      metadata: {
        lat: 51.5510, lng: -0.0980,
        venue: "HighburyFieldsLondon",
        deepLink: "https://clubspark.lta.org.uk/HighburyFieldsLondon/Booking/BookByDate",
        courts: 11, surface: "Tarmac", floodlit: true,
        note: "Requires ClubSpark login — cannot scrape anonymously",
      },
    },
    // Camden Active courts
    {
      name: "Lincoln's Inn Fields Tennis",
      slug: "lincolns-inn-fields",
      bookingSystem: "camden_active",
      bookingUrl: "https://camdenactive.camden.gov.uk/sports/lincolnsinnfields/",
      location: "Gate opposite Royal College of Surgeons, London WC2A",
      metadata: {
        lat: 51.5154, lng: -0.1176,
        venue: "lincolnsinnfields",
        deepLink: "https://camdenactive.camden.gov.uk/sports/lincolnsinnfields/",
        courts: 3, surface: "Tarmac",
        pricing: { standard: "£13.90", seniors: "£5.55", under16: "£5.55" },
        courtPages: [
          { id: 171, slug: "lincoln-s-inn-fields-tennis-court-1" },
          { id: 176, slug: "lincoln-s-inn-fields-tennis-court-2" },
          { id: 177, slug: "lincoln-s-inn-fields-tennis-court-3" },
        ],
      },
    },
    {
      name: "Waterlow Park Tennis",
      slug: "waterlow-park",
      bookingSystem: "camden_active",
      bookingUrl: "https://camdenactive.camden.gov.uk/sports/waterlow/",
      location: "Swains Lane / Highgate Hill, London N6",
      metadata: {
        lat: 51.5674, lng: -0.1449,
        venue: "waterlow",
        deepLink: "https://camdenactive.camden.gov.uk/sports/waterlow/",
        courts: 6, surface: "Tarmac",
        pricing: { standard: "£10.45", seniors: "£5.55", under16: "£5.55" },
        courtPages: [
          { id: 187, slug: "waterlow-park-tennis-court-1" },
          { id: 188, slug: "waterlow-park-tennis-court-2" },
          { id: 190, slug: "waterlow-park-tennis-court-3" },
          { id: 191, slug: "waterlow-park-tennis-court-4" },
          { id: 192, slug: "waterlow-park-tennis-court-5" },
          { id: 193, slug: "waterlow-park-tennis-court-6" },
        ],
      },
    },
    {
      name: "Kilburn Grange Park Tennis",
      slug: "kilburn-grange-park",
      bookingSystem: "camden_active",
      bookingUrl: "https://camdenactive.camden.gov.uk/sport/kilburngrange/",
      location: "Messina Avenue, London NW6",
      metadata: {
        lat: 51.5446, lng: -0.1959,
        venue: "kilburngrange",
        deepLink: "https://camdenactive.camden.gov.uk/sport/kilburngrange/",
        courts: 3, surface: "Tarmac",
        pricing: { standard: "£10.45", seniors: "£5.55", under16: "£5.55" },
        courtPages: [
          { id: 178, slug: "kilburn-grange-tennis-court-1" },
          { id: 179, slug: "kilburn-grange-tennis-court-2" },
          { id: 183, slug: "kilburn-grange-tennis-court-3" },
        ],
      },
    },
    // === West London — Kensington & Chelsea ===
    {
      name: "Holland Park Tennis",
      slug: "holland-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/hollandpark2/Booking/BookByDate",
      location: "Holland Park, London W8 6LU",
      metadata: {
        lat: 51.5020, lng: -0.2044,
        venue: "hollandpark2",
        deepLink: "https://clubspark.lta.org.uk/hollandpark2/Booking/BookByDate",
        courts: 6, surface: "Tarmac", floodlit: true,
        pricing: { peak: "£10.20", offPeak: "£6.65", floodlit: "£14.30" },
      },
    },
    {
      name: "Avondale Park Tennis",
      slug: "avondale-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/AvondalePark/Booking/BookByDate",
      location: "Avondale Park, London W11 4PQ",
      metadata: {
        lat: 51.5117, lng: -0.2091,
        venue: "AvondalePark",
        deepLink: "https://clubspark.lta.org.uk/AvondalePark/Booking/BookByDate",
        courts: 3, surface: "Artificial Turf",
      },
    },
    {
      name: "Kensington Memorial Park Tennis",
      slug: "kensington-memorial-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/KensingtonMemorialPark/Booking/BookByDate",
      location: "Kensington Memorial Park, London W10 6LH",
      metadata: {
        lat: 51.5155, lng: -0.2168,
        venue: "KensingtonMemorialPark",
        deepLink: "https://clubspark.lta.org.uk/KensingtonMemorialPark/Booking/BookByDate",
        courts: 3, surface: "Tarmac",
        pricing: { peak: "£10.20", offPeak: "£6.65" },
      },
    },
    // === West London — Hammersmith & Fulham ===
    {
      name: "Hurlingham Park Tennis",
      slug: "hurlingham-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/HurlinghamPark/Booking/BookByDate",
      location: "Hurlingham Park, London SW6",
      metadata: {
        lat: 51.4676, lng: -0.1943,
        venue: "HurlinghamPark",
        deepLink: "https://clubspark.lta.org.uk/HurlinghamPark/Booking/BookByDate",
        courts: 3, surface: "Synthetic Grass",
      },
    },
    {
      name: "Eel Brook Common Tennis",
      slug: "eel-brook-common",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/eelbrookcommon/Booking/BookByDate",
      location: "Eel Brook Common, London SW6 4QD",
      metadata: {
        lat: 51.4750, lng: -0.1920,
        venue: "eelbrookcommon",
        deepLink: "https://clubspark.lta.org.uk/eelbrookcommon/Booking/BookByDate",
        courts: 2,
      },
    },
    {
      name: "Linford Christie Stadium Tennis",
      slug: "linford-christie-stadium",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/LinfordChristieStadium/Booking/BookByDate",
      location: "Linford Christie Stadium, London W12 0DF",
      metadata: {
        lat: 51.5134, lng: -0.2300,
        venue: "LinfordChristieStadium",
        deepLink: "https://clubspark.lta.org.uk/LinfordChristieStadium/Booking/BookByDate",
        courts: 3, surface: "Tarmac", floodlit: true,
        pricing: { standard: "£11/hr" },
      },
    },
    {
      name: "Brook Green Tennis",
      slug: "brook-green",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/brookgreentennisclub/Booking/BookByDate",
      location: "Brook Green, London W14",
      metadata: {
        lat: 51.4943, lng: -0.2174,
        venue: "brookgreentennisclub",
        deepLink: "https://clubspark.lta.org.uk/brookgreentennisclub/Booking/BookByDate",
      },
    },
    // === West London — Ealing ===
    {
      name: "Acton Park Tennis",
      slug: "acton-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/ActonPark2/Booking/BookByDate",
      location: "Acton Park, London W3 7JX",
      metadata: {
        lat: 51.5087, lng: -0.2743,
        venue: "ActonPark2",
        deepLink: "https://clubspark.lta.org.uk/ActonPark2/Booking/BookByDate",
        courts: 2, surface: "Tarmac",
        pricing: { standard: "Free (booking required)" },
      },
    },
    {
      name: "Gunnersbury Park Sports Hub Tennis",
      slug: "gunnersbury-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/gunnersburypark/Booking/BookByDate",
      location: "Gunnersbury Park, London W3 8LQ",
      metadata: {
        lat: 51.4930, lng: -0.2870,
        venue: "gunnersburypark",
        deepLink: "https://clubspark.lta.org.uk/gunnersburypark/Booking/BookByDate",
        pricing: { day: "£8.50/hr", floodlit: "£10.60/hr" },
      },
    },
    {
      name: "North Acton Playing Fields Tennis",
      slug: "north-acton-playing-fields",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/NorthActonPlayingFieldsTennisClub/Booking/BookByDate",
      location: "North Acton Playing Fields, London W3 0JF",
      metadata: {
        lat: 51.5225, lng: -0.2670,
        venue: "NorthActonPlayingFieldsTennisClub",
        deepLink: "https://clubspark.lta.org.uk/NorthActonPlayingFieldsTennisClub/Booking/BookByDate",
        courts: 5,
        pricing: { standard: "£8/hr" },
      },
    },
    {
      name: "Southall Park Tennis",
      slug: "southall-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/SouthallPark2/Booking/BookByDate",
      location: "Southall Park, Southall UB1 3BT",
      metadata: {
        lat: 51.5104, lng: -0.3747,
        venue: "SouthallPark2",
        deepLink: "https://clubspark.lta.org.uk/SouthallPark2/Booking/BookByDate",
        pricing: { standard: "Free (booking required)" },
      },
    },
    {
      name: "Perivale Park Tennis",
      slug: "perivale-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/PerivalePark/Booking/BookByDate",
      location: "Perivale Park, Greenford UB6 8TJ",
      metadata: {
        lat: 51.5360, lng: -0.3230,
        venue: "PerivalePark",
        deepLink: "https://clubspark.lta.org.uk/PerivalePark/Booking/BookByDate",
        pricing: { standard: "Free (booking required)" },
      },
    },
    // === West London — Richmond ===
    {
      name: "Palewell Common Tennis",
      slug: "palewell-common",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/PalewellCommon/Booking/BookByDate",
      location: "Palewell Common, London SW14 8RF",
      metadata: {
        lat: 51.4600, lng: -0.2630,
        venue: "PalewellCommon",
        deepLink: "https://clubspark.lta.org.uk/PalewellCommon/Booking/BookByDate",
        courts: 4,
        pricing: { standard: "£11/hr" },
      },
    },
    {
      name: "Old Deer Park Tennis",
      slug: "old-deer-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/OldDeerPark/Booking/BookByDate",
      location: "Old Deer Park, Richmond TW9 2SF",
      metadata: {
        lat: 51.4690, lng: -0.3050,
        venue: "OldDeerPark",
        deepLink: "https://clubspark.lta.org.uk/OldDeerPark/Booking/BookByDate",
        pricing: { standard: "£11/hr" },
      },
    },
    {
      name: "Sheen Common Tennis",
      slug: "sheen-common",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/SheenCommon/Booking/BookByDate",
      location: "Sheen Common, London SW14 7ER",
      metadata: {
        lat: 51.4540, lng: -0.2560,
        venue: "SheenCommon",
        deepLink: "https://clubspark.lta.org.uk/SheenCommon/Booking/BookByDate",
        courts: 4,
        pricing: { standard: "£11/hr" },
      },
    },
    {
      name: "Carlisle Park Tennis",
      slug: "carlisle-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/CarlisleParkRichmond/Booking/BookByDate",
      location: "Carlisle Park, Hampton Hill TW12 2LY",
      metadata: {
        lat: 51.4210, lng: -0.3430,
        venue: "CarlisleParkRichmond",
        deepLink: "https://clubspark.lta.org.uk/CarlisleParkRichmond/Booking/BookByDate",
        courts: 7,
        pricing: { standard: "£11/hr" },
      },
    },
    {
      name: "Moor Mead Tennis",
      slug: "moor-mead",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/MoorMeadRecreationGround/Booking/BookByDate",
      location: "Moor Mead Recreation Ground, Twickenham TW1 1JS",
      metadata: {
        lat: 51.4510, lng: -0.3260,
        venue: "MoorMeadRecreationGround",
        deepLink: "https://clubspark.lta.org.uk/MoorMeadRecreationGround/Booking/BookByDate",
        courts: 4,
        pricing: { standard: "£11/hr" },
      },
    },
    // === West London — Wandsworth ===
    {
      name: "Battersea Park Tennis",
      slug: "battersea-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BatterseaParkTennisCourts/Booking/BookByDate",
      location: "Battersea Park, London SW11 4NJ",
      metadata: {
        lat: 51.4800, lng: -0.1560,
        venue: "BatterseaParkTennisCourts",
        deepLink: "https://clubspark.lta.org.uk/BatterseaParkTennisCourts/Booking/BookByDate",
        courts: 16, surface: "Tarmac & Astro", floodlit: true,
      },
    },
    {
      name: "Wimbledon Park Tennis",
      slug: "wimbledon-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/WimbledonPark/Booking/BookByDate",
      location: "Wimbledon Park, London SW19",
      metadata: {
        lat: 51.4340, lng: -0.1990,
        venue: "WimbledonPark",
        deepLink: "https://clubspark.lta.org.uk/WimbledonPark/Booking/BookByDate",
        pricing: { offPeak: "£10.70", peak: "£13.90" },
      },
    },
    // === West London — Brent ===
    {
      name: "Queen's Park Tennis",
      slug: "queens-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/QueensParkTennisCourts/Booking/BookByDate",
      location: "Queen's Park, London NW6",
      metadata: {
        lat: 51.5340, lng: -0.2050,
        venue: "QueensParkTennisCourts",
        deepLink: "https://clubspark.lta.org.uk/QueensParkTennisCourts/Booking/BookByDate",
        courts: 6,
        pricing: { standard: "£11.10/hr", concession: "£6.70/hr" },
      },
    },
    // === Hampstead Heath / NW London ===
    {
      name: "Parliament Hill Fields Tennis",
      slug: "parliament-hill-fields",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/ParliamentHillFieldsTennisCourts/Booking/BookByDate",
      location: "Parliament Hill Fields, Hampstead Heath, London NW5",
      metadata: {
        lat: 51.5570, lng: -0.1510,
        venue: "ParliamentHillFieldsTennisCourts",
        deepLink: "https://clubspark.lta.org.uk/ParliamentHillFieldsTennisCourts/Booking/BookByDate",
        courts: 10, surface: "Hard",
        pricing: { standard: "£11.10/hr", concession: "£6.70/hr" },
      },
    },
    {
      name: "Golders Hill Park Tennis",
      slug: "golders-hill-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/GoldersHillPark/Booking/BookByDate",
      location: "Golders Hill Park, Hampstead Heath, London NW11",
      metadata: {
        lat: 51.5710, lng: -0.1860,
        venue: "GoldersHillPark",
        deepLink: "https://clubspark.lta.org.uk/GoldersHillPark/Booking/BookByDate",
        pricing: { standard: "£11.10/hr", concession: "£6.70/hr" },
      },
    },
    {
      name: "Gladstone Park Tennis",
      slug: "gladstone-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/GladstoneParkTennis/Booking/BookByDate",
      location: "Gladstone Park, Dollis Hill, London NW2",
      metadata: {
        lat: 51.5530, lng: -0.2310,
        venue: "GladstoneParkTennis",
        deepLink: "https://clubspark.lta.org.uk/GladstoneParkTennis/Booking/BookByDate",
        courts: 8, surface: "Macadam",
      },
    },
    {
      name: "Ravenscourt Park Tennis",
      slug: "ravenscourt-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/RavenscourtPark/Booking/BookByDate",
      location: "Ravenscourt Park, London W6",
      metadata: {
        lat: 51.4940, lng: -0.2370,
        venue: "RavenscourtPark",
        deepLink: "https://clubspark.lta.org.uk/RavenscourtPark/Booking/BookByDate",
        courts: 7, surface: "Tarmac",
      },
    },
    // === Greenwich ===
    {
      name: "Blackheath Tennis",
      slug: "blackheath",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BlackheathPark/Booking/BookByDate",
      location: "Chesterfield Walk, Blackheath, London SE10 8QX",
      metadata: {
        lat: 51.4680, lng: 0.0050,
        venue: "BlackheathPark",
        deepLink: "https://clubspark.lta.org.uk/BlackheathPark/Booking/BookByDate",
        courts: 3, surface: "Hard",
        pricing: { adult: "£6.30/hr", junior: "£4.20/hr" },
      },
    },
    {
      name: "Maryon Park Tennis",
      slug: "maryon-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/MaryonPark/Booking/BookByDate",
      location: "Maryon Park, Charlton, London SE7",
      metadata: {
        lat: 51.4860, lng: 0.0250,
        venue: "MaryonPark",
        deepLink: "https://clubspark.lta.org.uk/MaryonPark/Booking/BookByDate",
        pricing: { standard: "£3/hr" },
      },
    },
    {
      name: "Plumstead Common Tennis",
      slug: "plumstead-common",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/PlumsteadCommon/Booking/BookByDate",
      location: "Plumstead Common, London SE18",
      metadata: {
        lat: 51.4810, lng: 0.0540,
        venue: "PlumsteadCommon",
        deepLink: "https://clubspark.lta.org.uk/PlumsteadCommon/Booking/BookByDate",
        pricing: { standard: "£3/hr" },
      },
    },
    {
      name: "Kidbrooke Green Tennis",
      slug: "kidbrooke-green",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/KidbrookeGreen/Booking/BookByDate",
      location: "Kidbrooke Green, London SE9",
      metadata: {
        lat: 51.4510, lng: 0.0360,
        venue: "KidbrookeGreen",
        deepLink: "https://clubspark.lta.org.uk/KidbrookeGreen/Booking/BookByDate",
        pricing: { standard: "£3/hr" },
      },
    },
    {
      name: "Bostall Gardens Tennis",
      slug: "bostall-gardens",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BostallGardens/Booking/BookByDate",
      location: "Bostall Gardens, London SE2",
      metadata: {
        lat: 51.4760, lng: 0.0760,
        venue: "BostallGardens",
        deepLink: "https://clubspark.lta.org.uk/BostallGardens/Booking/BookByDate",
        pricing: { standard: "£3/hr" },
      },
    },
    {
      name: "Altash Gardens Tennis",
      slug: "altash-gardens",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/AltashGardens/Booking/BookByDate",
      location: "Altash Gardens, London SE9 3AL",
      metadata: {
        lat: 51.4530, lng: 0.0720,
        venue: "AltashGardens",
        deepLink: "https://clubspark.lta.org.uk/AltashGardens/Booking/BookByDate",
        pricing: { standard: "£3/hr" },
      },
    },
    // === Southwark ===
    {
      name: "Burgess Park Tennis",
      slug: "burgess-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BurgessParkSouthwark/Booking/BookByDate",
      location: "Burgess Park, London SE5 7LA",
      metadata: {
        lat: 51.4860, lng: -0.0780,
        venue: "BurgessParkSouthwark",
        deepLink: "https://clubspark.lta.org.uk/BurgessParkSouthwark/Booking/BookByDate",
        courts: 7, floodlit: true,
        pricing: { peak: "£9.40/hr", offPeak: "£6.80/hr" },
      },
    },
    {
      name: "Dulwich Park Tennis",
      slug: "dulwich-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/DulwichPark/Booking/BookByDate",
      location: "Dulwich Park, London SE21 7EB",
      metadata: {
        lat: 51.4500, lng: -0.0780,
        venue: "DulwichPark",
        deepLink: "https://clubspark.lta.org.uk/DulwichPark/Booking/BookByDate",
        courts: 4,
        pricing: { peak: "£9.40/hr", offPeak: "£6.80/hr" },
      },
    },
    {
      name: "Belair Park Tennis",
      slug: "belair-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BelairPark/Booking/BookByDate",
      location: "Belair Park, London SE21 7EX",
      metadata: {
        lat: 51.4460, lng: -0.0870,
        venue: "BelairPark",
        deepLink: "https://clubspark.lta.org.uk/BelairPark/Booking/BookByDate",
        pricing: { peak: "£9.40/hr", offPeak: "£6.80/hr" },
      },
    },
    {
      name: "Tanner Street Park Tennis",
      slug: "tanner-street-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/TannerStPark/Booking/BookByDate",
      location: "Tanner Street Park, Bermondsey, London SE1 3LL",
      metadata: {
        lat: 51.4990, lng: -0.0770,
        venue: "TannerStPark",
        deepLink: "https://clubspark.lta.org.uk/TannerStPark/Booking/BookByDate",
        pricing: { peak: "£9.40/hr", offPeak: "£6.80/hr" },
      },
    },
    {
      name: "Brunswick Park Tennis",
      slug: "brunswick-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BrunswickParkSouthwark/Booking/BookByDate",
      location: "Brunswick Park, London SE5 7RH",
      metadata: {
        lat: 51.4780, lng: -0.0830,
        venue: "BrunswickParkSouthwark",
        deepLink: "https://clubspark.lta.org.uk/BrunswickParkSouthwark/Booking/BookByDate",
        pricing: { peak: "£9.40/hr", offPeak: "£6.80/hr" },
      },
    },
    // === Lambeth ===
    {
      name: "Ruskin Park Tennis",
      slug: "ruskin-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/ruskinpark/Booking/BookByDate",
      location: "Ruskin Park, Denmark Hill, London SE5 8EL",
      metadata: {
        lat: 51.4680, lng: -0.0880,
        venue: "ruskinpark",
        deepLink: "https://clubspark.lta.org.uk/ruskinpark/Booking/BookByDate",
      },
    },
    {
      name: "Vauxhall Park Tennis",
      slug: "vauxhall-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/vauxhallpark/Booking/BookByDate",
      location: "Vauxhall Park, London SW8 1UD",
      metadata: {
        lat: 51.4820, lng: -0.1180,
        venue: "vauxhallpark",
        deepLink: "https://clubspark.lta.org.uk/vauxhallpark/Booking/BookByDate",
        courts: 2,
      },
    },
    {
      name: "Hillside Gardens Park Tennis",
      slug: "hillside-gardens-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/HillsideGardensPark/Booking/BookByDate",
      location: "Hillside Gardens Park, London SW2 3HL",
      metadata: {
        lat: 51.4500, lng: -0.1170,
        venue: "HillsideGardensPark",
        deepLink: "https://clubspark.lta.org.uk/HillsideGardensPark/Booking/BookByDate",
        courts: 4,
      },
    },
    // === East London ===
    {
      name: "West Ham Park Tennis",
      slug: "west-ham-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/westhampark/Booking/BookByDate",
      location: "West Ham Park, London E15",
      metadata: {
        lat: 51.5400, lng: 0.0130,
        venue: "westhampark",
        deepLink: "https://clubspark.lta.org.uk/westhampark/Booking/BookByDate",
        courts: 6, surface: "Hard",
        pricing: { standard: "£7.60/hr", concession: "£4.60/hr" },
      },
    },
    {
      name: "Honor Oak Recreation Ground Tennis",
      slug: "honor-oak",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/HonorOakRecreationGround/Booking/BookByDate",
      location: "Honor Oak Recreation Ground, London SE23 3LB",
      metadata: {
        lat: 51.4490, lng: -0.0490,
        venue: "HonorOakRecreationGround",
        deepLink: "https://clubspark.lta.org.uk/HonorOakRecreationGround/Booking/BookByDate",
        pricing: { peak: "£9.40/hr", offPeak: "£6.80/hr" },
      },
    },
    // === Royal Parks (Flow.onl) ===
    {
      name: "Hyde Park Tennis",
      slug: "hyde-park",
      bookingSystem: "flow_onl",
      bookingUrl: "https://sportsandleisureroyalparks.bookings.flow.onl/location/hyde-park-courts/tennis",
      location: "Hyde Park, South Carriage Drive, London W2 2UH",
      metadata: {
        lat: 51.5053, lng: -0.1657,
        venue: "hyde-park-courts",
        deepLink: "https://sportsandleisureroyalparks.bookings.flow.onl/location/hyde-park-courts/tennis",
        courts: 6, floodlit: true,
      },
    },
    {
      name: "Regent's Park Tennis",
      slug: "regents-park",
      bookingSystem: "flow_onl",
      bookingUrl: "https://sportsandleisureroyalparks.bookings.flow.onl/location/the-regents-park-courts/tennis",
      location: "The Regent's Park, York Bridge, London NW1 4NR",
      metadata: {
        lat: 51.5270, lng: -0.1534,
        venue: "the-regents-park-courts",
        deepLink: "https://sportsandleisureroyalparks.bookings.flow.onl/location/the-regents-park-courts/tennis",
        courts: 12, floodlit: true,
      },
    },
    {
      name: "Greenwich Park Tennis",
      slug: "greenwich-park",
      bookingSystem: "flow_onl",
      bookingUrl: "https://sportsandleisureroyalparks.bookings.flow.onl/location/greenwich-park-courts/tennis",
      location: "Greenwich Park, Blackheath Avenue, London SE10 8QY",
      metadata: {
        lat: 51.4769, lng: -0.0005,
        venue: "greenwich-park-courts",
        deepLink: "https://sportsandleisureroyalparks.bookings.flow.onl/location/greenwich-park-courts/tennis",
        courts: 6,
      },
    },
  ];

  console.log("Seeding courts...");

  for (const court of courts) {
    const existing = await prisma.court.findUnique({ where: { slug: court.slug } });
    if (existing) {
      console.log(`  Skipping ${court.name} (already exists)`);
      continue;
    }
    await prisma.court.create({ data: court });
    console.log(`  Created ${court.name}`);
  }

  console.log("Done!");
  await prisma.$disconnect();
}

main().catch(console.error);
