import "dotenv/config";

async function main() {
  const { PrismaClient } = await import("../src/generated/prisma/client.js");
  const { PrismaPg } = await import("@prisma/adapter-pg");

  const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
  const prisma = new PrismaClient({ adapter });

  const courts = [
    {
      name: "Garden Halls Tennis",
      slug: "garden-halls",
      bookingSystem: "microsoft_bookings",
      bookingUrl: "https://outlook.office365.com/owa/calendar/GardenHallsTennis@upp-ltd.com/bookings/",
      location: "Garden Halls, Cartwright Gardens, London WC1H 9EN",
      metadata: {
        lat: 51.526756, lng: -0.126931,
        serviceTypes: [
          { name: "Garden Halls Resident", duration: "1 hour", price: "Free" },
          { name: "Student", duration: "1 hour", price: "£5/hr" },
          { name: "WC1 Resident", duration: "1 hour", price: "£5/hr" },
          { name: "Visitor", duration: "1 hour", price: "£10/hr" },
        ],
      },
    },
    {
      name: "Islington Tennis Centre",
      slug: "islington-tennis-centre",
      bookingSystem: "better",
      bookingUrl: "https://bookings.better.org.uk/location/islington-tennis-centre/tennis-activities",
      location: "Market Road, London N7 9PL",
      metadata: {
        lat: 51.545681, lng: -0.122495,
        activity: "tennis-court-outdoor",
        venue: "islington-tennis-centre",
        deepLink: "https://bookings.better.org.uk/location/islington-tennis-centre/tennis-court-outdoor",
        activities: ["tennis-court-outdoor", "tennis-court-indoor"],
      },
    },
    // ClubSpark courts
    {
      name: "Finsbury Park Tennis",
      slug: "finsbury-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/FinsburyPark/Booking/BookByDate",
      location: "Finsbury Park, London N4 2DE",
      metadata: {
        lat: 51.567966, lng: -0.104544,
        venue: "FinsburyPark",
        deepLink: "https://clubspark.lta.org.uk/FinsburyPark/Booking/BookByDate",
        courts: 8, surface: "Hard", floodlit: true,
        pricing: { offPeak: "£4", peak: "£7" },
      },
    },
    // Disabled: requires ClubSpark login
    {
      name: "Paddington Recreation Ground",
      slug: "paddington-recreation-ground",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/PaddingtonRecreationGround/Booking/BookByDate",
      location: "Randolph Avenue, London W9 1PD",
      enabled: false,
      metadata: {
        lat: 51.530517, lng: -0.188061,
        venue: "PaddingtonRecreationGround",
        deepLink: "https://clubspark.lta.org.uk/PaddingtonRecreationGround/Booking/BookByDate",
        courts: 13, surface: "Tarmac & Synthetic", floodlit: true,
        pricing: { nonMember: "£8-10/hr" },
        note: "Requires ClubSpark login — cannot scrape anonymously",
      },
    },
    // Disabled: requires ClubSpark login
    {
      name: "Rosemary Gardens Tennis",
      slug: "rosemary-gardens",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/RosemaryGardens/Booking/BookByDate",
      location: "Southgate Road, London N1 3JP",
      enabled: false,
      metadata: {
        lat: 51.538635, lng: -0.088458,
        venue: "RosemaryGardens",
        deepLink: "https://clubspark.lta.org.uk/RosemaryGardens/Booking/BookByDate",
        courts: 2, surface: "Tarmac",
        note: "Requires ClubSpark login — cannot scrape anonymously",
      },
    },
    {
      name: "Clissold Park Tennis",
      slug: "clissold-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/ClissoldParkHackney/Booking/BookByDate",
      location: "Clissold Park, London N16 0BF",
      metadata: {
        lat: 51.562425, lng: -0.085177,
        venue: "ClissoldParkHackney",
        deepLink: "https://clubspark.lta.org.uk/ClissoldParkHackney/Booking/BookByDate",
        courts: 7, floodlit: true,
        pricing: { offPeak: "£4-5" },
      },
    },
    {
      name: "Hackney Downs Park Tennis",
      slug: "hackney-downs",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/HackneyDowns/Booking/BookByDate",
      location: "Hackney Downs, London N16",
      metadata: {
        lat: 51.553048, lng: -0.060140,
        venue: "HackneyDowns",
        deepLink: "https://clubspark.lta.org.uk/HackneyDowns/Booking/BookByDate",
        courts: 5, floodlit: true,
        pricing: { offPeak: "£4-5" },
      },
    },
    {
      name: "London Fields Tennis",
      slug: "london-fields",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/LondonFieldsPark/Booking/BookByDate",
      location: "London Fields, London E8",
      metadata: {
        lat: 51.543269, lng: -0.061104,
        venue: "LondonFieldsPark",
        deepLink: "https://clubspark.lta.org.uk/LondonFieldsPark/Booking/BookByDate",
        courts: 2, surface: "Porous Macadam",
        pricing: { adult: "£4.50/hr" },
      },
    },
    {
      name: "Geraldine Mary Harmsworth Park Tennis",
      slug: "geraldine-mary-harmsworth",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/GeraldineMaryHarmsworth/Booking/BookByDate",
      location: "St George's Road, London SE1 6HZ",
      metadata: {
        lat: 51.496286, lng: -0.106161,
        venue: "GeraldineMaryHarmsworth",
        deepLink: "https://clubspark.lta.org.uk/GeraldineMaryHarmsworth/Booking/BookByDate",
        courts: 2, floodlit: true, surface: "All-weather",
      },
    },
    // Disabled: Tennis In Lambeth requires ClubSpark login
    {
      name: "Archbishop's Park Tennis",
      slug: "archbishops-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/TennisInLambeth/Booking/BookByDate",
      location: "Lambeth Palace Road, London SE1 7LQ",
      enabled: false,
      metadata: {
        lat: 51.497794, lng: -0.115971,
        venue: "TennisInLambeth",
        deepLink: "https://clubspark.lta.org.uk/TennisInLambeth/Booking/BookByDate",
        courts: 2, surface: "Tarmac",
        note: "Requires ClubSpark login — cannot scrape anonymously",
      },
    },
    // Disabled: Tennis In Lambeth requires ClubSpark login
    {
      name: "Kennington Park Tennis",
      slug: "kennington-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/TennisInLambeth/Booking/BookByDate",
      location: "Kennington Park Road, London SE11 4BE",
      enabled: false,
      metadata: {
        lat: 51.482193, lng: -0.109684,
        venue: "TennisInLambeth",
        deepLink: "https://clubspark.lta.org.uk/TennisInLambeth/Booking/BookByDate",
        courts: 4, surface: "Tarmac", floodlit: true,
        note: "Requires ClubSpark login — cannot scrape anonymously",
      },
    },
    {
      name: "Spring Hill Tennis",
      slug: "spring-hill",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/SpringHillParkTennis/Booking/BookByDate",
      location: "Spring Hill, Hackney, London",
      metadata: {
        lat: 51.553653, lng: -0.051444,
        venue: "SpringHillParkTennis",
        deepLink: "https://clubspark.lta.org.uk/SpringHillParkTennis/Booking/BookByDate",
        courts: 2, surface: "Tarmac",
        pricing: { adult: "£3.90/hr" },
      },
    },
    {
      name: "Elthorne Tennis Club",
      slug: "elthorne-tennis",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/ElthorneTennis/Booking/BookByDate",
      location: "Elthorne Park, Haringey, London",
      metadata: {
        lat: 51.576273, lng: -0.131025,
        venue: "ElthorneTennis",
        deepLink: "https://clubspark.lta.org.uk/ElthorneTennis/Booking/BookByDate",
        courts: 3, floodlit: true,
        pricing: { nonMember: "£8.70/hr", floodlit: "£11.70/hr" },
      },
    },
    // Millfields Park removed — ClubSpark URL returns 404
    {
      name: "Southwark Park Tennis",
      slug: "southwark-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/SouthwarkPark/Booking/BookByDate",
      location: "Jamaica Gate entrance, London SE16",
      metadata: {
        lat: 51.495907, lng: -0.058301,
        venue: "SouthwarkPark",
        deepLink: "https://clubspark.lta.org.uk/SouthwarkPark/Booking/BookByDate",
        courts: 4, surface: "Tarmac",
      },
    },
    {
      name: "Clapham Common Tennis",
      slug: "clapham-common",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/claphamcommon/Booking/BookByDate",
      location: "Windmill Drive, London SW4 9AN",
      metadata: {
        lat: 51.454502, lng: -0.150650,
        venue: "claphamcommon",
        deepLink: "https://clubspark.lta.org.uk/claphamcommon/Booking/BookByDate",
        courts: 8, floodlit: true,
      },
    },
    // Tower Hamlets courts (migrated from Courtside to ClubSpark)
    {
      name: "Bethnal Green Gardens Tennis",
      slug: "bethnal-green-gardens",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BethnalGreenGardens/Booking/BookByDate",
      location: "Malcolm Place, London E2 0EU",
      metadata: {
        lat: 51.526894, lng: -0.070646,
        venue: "BethnalGreenGardens",
        deepLink: "https://clubspark.lta.org.uk/BethnalGreenGardens/Booking/BookByDate",
        courts: 4, surface: "Hard", floodlit: true,
        pricing: { adult: "£4-6" },
      },
    },
    {
      name: "King Edward Memorial Park Tennis",
      slug: "king-edward-memorial",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/KingEdwardMemorialPark/Booking/BookByDate",
      location: "Glamis Road, London E1W 3TD",
      metadata: {
        lat: 51.509016, lng: -0.049898,
        venue: "KingEdwardMemorialPark",
        deepLink: "https://clubspark.lta.org.uk/KingEdwardMemorialPark/Booking/BookByDate",
        courts: 4, surface: "Porous Macadam",
        pricing: { adult: "£4-6" },
      },
    },
    // Disabled: requires ClubSpark login
    {
      name: "St John's Park Tennis",
      slug: "st-johns-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/StJohnsPark/Booking/BookByDate",
      location: "Plevna Street, Tower Hamlets, London",
      enabled: false,
      metadata: {
        lat: 51.519264, lng: -0.024375,
        venue: "StJohnsPark",
        deepLink: "https://clubspark.lta.org.uk/StJohnsPark/Booking/BookByDate",
        courts: 2, floodlit: true,
        pricing: { offPeak: "£4", peak: "£6" },
        note: "Requires ClubSpark login — cannot scrape anonymously",
      },
    },
    // Disabled: requires ClubSpark login (Better URL defunct)
    {
      name: "Highbury Fields Tennis",
      slug: "highbury-fields",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/HighburyFieldsLondon/Booking/BookByDate",
      location: "Highbury Fields, London N5",
      enabled: false,
      metadata: {
        lat: 51.550869, lng: -0.099089,
        venue: "HighburyFieldsLondon",
        deepLink: "https://clubspark.lta.org.uk/HighburyFieldsLondon/Booking/BookByDate",
        courts: 11, surface: "Tarmac", floodlit: true,
        note: "Requires ClubSpark login — cannot scrape anonymously",
      },
    },
    // Camden Active courts
    {
      name: "Lincoln's Inn Fields Tennis",
      slug: "lincolns-inn-fields",
      bookingSystem: "camden_active",
      bookingUrl: "https://camdenactive.camden.gov.uk/sports/lincolnsinnfields/",
      location: "Gate opposite Royal College of Surgeons, London WC2A",
      metadata: {
        lat: 51.515784, lng: -0.116903,
        venue: "lincolnsinnfields",
        deepLink: "https://camdenactive.camden.gov.uk/sports/lincolnsinnfields/",
        courts: 3, surface: "Tarmac",
        pricing: { standard: "£13.90", seniors: "£5.55", under16: "£5.55" },
        courtPages: [
          { id: 171, slug: "lincoln-s-inn-fields-tennis-court-1" },
          { id: 176, slug: "lincoln-s-inn-fields-tennis-court-2" },
          { id: 177, slug: "lincoln-s-inn-fields-tennis-court-3" },
        ],
      },
    },
    {
      name: "Waterlow Park Tennis",
      slug: "waterlow-park",
      bookingSystem: "camden_active",
      bookingUrl: "https://camdenactive.camden.gov.uk/sports/waterlow/",
      location: "Swains Lane / Highgate Hill, London N6",
      metadata: {
        lat: 51.569473, lng: -0.145047,
        venue: "waterlow",
        deepLink: "https://camdenactive.camden.gov.uk/sports/waterlow/",
        courts: 6, surface: "Tarmac",
        pricing: { standard: "£10.45", seniors: "£5.55", under16: "£5.55" },
        courtPages: [
          { id: 187, slug: "waterlow-park-tennis-court-1" },
          { id: 188, slug: "waterlow-park-tennis-court-2" },
          { id: 190, slug: "waterlow-park-tennis-court-3" },
          { id: 191, slug: "waterlow-park-tennis-court-4" },
          { id: 192, slug: "waterlow-park-tennis-court-5" },
          { id: 193, slug: "waterlow-park-tennis-court-6" },
        ],
      },
    },
    {
      name: "Kilburn Grange Park Tennis",
      slug: "kilburn-grange-park",
      bookingSystem: "camden_active",
      bookingUrl: "https://camdenactive.camden.gov.uk/sport/kilburngrange/",
      location: "Messina Avenue, London NW6",
      metadata: {
        lat: 51.542896, lng: -0.197600,
        venue: "kilburngrange",
        deepLink: "https://camdenactive.camden.gov.uk/sport/kilburngrange/",
        courts: 3, surface: "Tarmac",
        pricing: { standard: "£10.45", seniors: "£5.55", under16: "£5.55" },
        courtPages: [
          { id: 178, slug: "kilburn-grange-tennis-court-1" },
          { id: 179, slug: "kilburn-grange-tennis-court-2" },
          { id: 183, slug: "kilburn-grange-tennis-court-3" },
        ],
      },
    },
    // === West London — Kensington & Chelsea ===
    {
      name: "Holland Park Tennis",
      slug: "holland-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/hollandpark2/Booking/BookByDate",
      location: "Holland Park, London W8 6LU",
      metadata: {
        lat: 51.500972, lng: -0.204273,
        venue: "hollandpark2",
        deepLink: "https://clubspark.lta.org.uk/hollandpark2/Booking/BookByDate",
        courts: 6, surface: "Tarmac", floodlit: true,
        pricing: { peak: "£10.20", offPeak: "£6.65", floodlit: "£14.30" },
      },
    },
    {
      name: "Avondale Park Tennis",
      slug: "avondale-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/AvondalePark/Booking/BookByDate",
      location: "Avondale Park, London W11 4PQ",
      metadata: {
        lat: 51.510764, lng: -0.212566,
        venue: "AvondalePark",
        deepLink: "https://clubspark.lta.org.uk/AvondalePark/Booking/BookByDate",
        courts: 3, surface: "Artificial Turf",
      },
    },
    {
      name: "Kensington Memorial Park Tennis",
      slug: "kensington-memorial-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/KensingtonMemorialPark/Booking/BookByDate",
      location: "Kensington Memorial Park, London W10 6LH",
      metadata: {
        lat: 51.514525, lng: -0.220383,
        venue: "KensingtonMemorialPark",
        deepLink: "https://clubspark.lta.org.uk/KensingtonMemorialPark/Booking/BookByDate",
        courts: 3, surface: "Tarmac",
        pricing: { peak: "£10.20", offPeak: "£6.65" },
      },
    },
    // === West London — Hammersmith & Fulham ===
    {
      name: "Hurlingham Park Tennis",
      slug: "hurlingham-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/HurlinghamPark/Booking/BookByDate",
      location: "Hurlingham Park, London SW6",
      metadata: {
        lat: 51.467460, lng: -0.193456,
        venue: "HurlinghamPark",
        deepLink: "https://clubspark.lta.org.uk/HurlinghamPark/Booking/BookByDate",
        courts: 3, surface: "Synthetic Grass",
      },
    },
    {
      name: "Eel Brook Common Tennis",
      slug: "eel-brook-common",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/eelbrookcommon/Booking/BookByDate",
      location: "Eel Brook Common, London SW6 4QD",
      metadata: {
        lat: 51.476218, lng: -0.195716,
        venue: "eelbrookcommon",
        deepLink: "https://clubspark.lta.org.uk/eelbrookcommon/Booking/BookByDate",
        courts: 2,
      },
    },
    {
      name: "Linford Christie Stadium Tennis",
      slug: "linford-christie-stadium",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/LinfordChristieStadium/Booking/BookByDate",
      location: "Linford Christie Stadium, London W12 0DF",
      metadata: {
        lat: 51.510641, lng: -0.228371,
        venue: "LinfordChristieStadium",
        deepLink: "https://clubspark.lta.org.uk/LinfordChristieStadium/Booking/BookByDate",
        courts: 3, surface: "Tarmac", floodlit: true,
        pricing: { standard: "£11/hr" },
      },
    },
    {
      name: "Brook Green Tennis",
      slug: "brook-green",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/brookgreentennisclub/Booking/BookByDate",
      location: "Brook Green, London W14",
      metadata: {
        lat: 51.495097, lng: -0.221977,
        venue: "brookgreentennisclub",
        deepLink: "https://clubspark.lta.org.uk/brookgreentennisclub/Booking/BookByDate",
      },
    },
    // === West London — Ealing ===
    {
      name: "Acton Park Tennis",
      slug: "acton-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/ActonPark2/Booking/BookByDate",
      location: "Acton Park, London W3 7JX",
      metadata: {
        lat: 51.505623, lng: -0.281564,
        venue: "ActonPark2",
        deepLink: "https://clubspark.lta.org.uk/ActonPark2/Booking/BookByDate",
        courts: 2, surface: "Tarmac",
        pricing: { standard: "Free (booking required)" },
      },
    },
    {
      name: "Gunnersbury Park Sports Hub Tennis",
      slug: "gunnersbury-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/gunnersburypark/Booking/BookByDate",
      location: "Gunnersbury Park, London W3 8LQ",
      metadata: {
        lat: 51.485939, lng: -0.287221,
        venue: "gunnersburypark",
        deepLink: "https://clubspark.lta.org.uk/gunnersburypark/Booking/BookByDate",
        pricing: { day: "£8.50/hr", floodlit: "£10.60/hr" },
      },
    },
    {
      name: "North Acton Playing Fields Tennis",
      slug: "north-acton-playing-fields",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/NorthActonPlayingFieldsTennisClub/Booking/BookByDate",
      location: "North Acton Playing Fields, London W3 0JF",
      metadata: {
        lat: 51.519828, lng: -0.269382,
        venue: "NorthActonPlayingFieldsTennisClub",
        deepLink: "https://clubspark.lta.org.uk/NorthActonPlayingFieldsTennisClub/Booking/BookByDate",
        courts: 5,
        pricing: { standard: "£8/hr" },
      },
    },
    {
      name: "Southall Park Tennis",
      slug: "southall-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/SouthallPark2/Booking/BookByDate",
      location: "Southall Park, Southall UB1 3BT",
      metadata: {
        lat: 51.508480, lng: -0.372868,
        venue: "SouthallPark2",
        deepLink: "https://clubspark.lta.org.uk/SouthallPark2/Booking/BookByDate",
        pricing: { standard: "Free (booking required)" },
      },
    },
    {
      name: "Perivale Park Tennis",
      slug: "perivale-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/PerivalePark/Booking/BookByDate",
      location: "Perivale Park, Greenford UB6 8TJ",
      metadata: {
        lat: 51.531787, lng: -0.327495,
        venue: "PerivalePark",
        deepLink: "https://clubspark.lta.org.uk/PerivalePark/Booking/BookByDate",
        pricing: { standard: "Free (booking required)" },
      },
    },
    // === West London — Richmond ===
    {
      name: "Palewell Common Tennis",
      slug: "palewell-common",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/PalewellCommon/Booking/BookByDate",
      location: "Palewell Common, London SW14 8RF",
      metadata: {
        lat: 51.459500, lng: -0.261167,
        venue: "PalewellCommon",
        deepLink: "https://clubspark.lta.org.uk/PalewellCommon/Booking/BookByDate",
        courts: 4,
        pricing: { standard: "£11/hr" },
      },
    },
    {
      name: "Old Deer Park Tennis",
      slug: "old-deer-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/OldDeerPark/Booking/BookByDate",
      location: "Old Deer Park, Richmond TW9 2SF",
      metadata: {
        lat: 51.465742, lng: -0.308266,
        venue: "OldDeerPark",
        deepLink: "https://clubspark.lta.org.uk/OldDeerPark/Booking/BookByDate",
        pricing: { standard: "£11/hr" },
      },
    },
    {
      name: "Sheen Common Tennis",
      slug: "sheen-common",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/SheenCommon/Booking/BookByDate",
      location: "Sheen Common, London SW14 7ER",
      metadata: {
        lat: 51.455598, lng: -0.255458,
        venue: "SheenCommon",
        deepLink: "https://clubspark.lta.org.uk/SheenCommon/Booking/BookByDate",
        courts: 4,
        pricing: { standard: "£11/hr" },
      },
    },
    {
      name: "Carlisle Park Tennis",
      slug: "carlisle-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/CarlisleParkRichmond/Booking/BookByDate",
      location: "Carlisle Park, Hampton Hill TW12 2LY",
      metadata: {
        lat: 51.420555, lng: -0.335397,
        venue: "CarlisleParkRichmond",
        deepLink: "https://clubspark.lta.org.uk/CarlisleParkRichmond/Booking/BookByDate",
        courts: 7,
        pricing: { standard: "£11/hr" },
      },
    },
    {
      name: "Moor Mead Tennis",
      slug: "moor-mead",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/MoorMeadRecreationGround/Booking/BookByDate",
      location: "Moor Mead Recreation Ground, Twickenham TW1 1JS",
      metadata: {
        lat: 51.450750, lng: -0.324943,
        venue: "MoorMeadRecreationGround",
        deepLink: "https://clubspark.lta.org.uk/MoorMeadRecreationGround/Booking/BookByDate",
        courts: 4,
        pricing: { standard: "£11/hr" },
      },
    },
    // === West London — Wandsworth ===
    {
      name: "Battersea Park Tennis",
      slug: "battersea-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BatterseaParkTennisCourts/Booking/BookByDate",
      location: "Battersea Park, London SW11 4NJ",
      metadata: {
        lat: 51.481325, lng: -0.154343,
        venue: "BatterseaParkTennisCourts",
        deepLink: "https://clubspark.lta.org.uk/BatterseaParkTennisCourts/Booking/BookByDate",
        courts: 16, surface: "Tarmac & Astro", floodlit: true,
      },
    },
    {
      name: "Wimbledon Park Tennis",
      slug: "wimbledon-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/WimbledonPark/Booking/BookByDate",
      location: "Wimbledon Park, London SW19",
      metadata: {
        lat: 51.436059, lng: -0.202699,
        venue: "WimbledonPark",
        deepLink: "https://clubspark.lta.org.uk/WimbledonPark/Booking/BookByDate",
        pricing: { offPeak: "£10.70", peak: "£13.90" },
      },
    },
    // === West London — Brent ===
    {
      name: "Queen's Park Tennis",
      slug: "queens-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/QueensParkTennisCourts/Booking/BookByDate",
      location: "Queen's Park, London NW6",
      metadata: {
        lat: 51.535906, lng: -0.211829,
        venue: "QueensParkTennisCourts",
        deepLink: "https://clubspark.lta.org.uk/QueensParkTennisCourts/Booking/BookByDate",
        courts: 6,
        pricing: { standard: "£11.10/hr", concession: "£6.70/hr" },
      },
    },
    // === Hampstead Heath / NW London ===
    {
      name: "Parliament Hill Fields Tennis",
      slug: "parliament-hill-fields",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/ParliamentHillFieldsTennisCourts/Booking/BookByDate",
      location: "Parliament Hill Fields, Hampstead Heath, London NW5",
      metadata: {
        lat: 51.557156, lng: -0.149754,
        venue: "ParliamentHillFieldsTennisCourts",
        deepLink: "https://clubspark.lta.org.uk/ParliamentHillFieldsTennisCourts/Booking/BookByDate",
        courts: 10, surface: "Hard",
        pricing: { standard: "£11.10/hr", concession: "£6.70/hr" },
      },
    },
    {
      name: "Golders Hill Park Tennis",
      slug: "golders-hill-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/GoldersHillPark/Booking/BookByDate",
      location: "Golders Hill Park, Hampstead Heath, London NW11",
      metadata: {
        lat: 51.573723, lng: -0.189007,
        venue: "GoldersHillPark",
        deepLink: "https://clubspark.lta.org.uk/GoldersHillPark/Booking/BookByDate",
        pricing: { standard: "£11.10/hr", concession: "£6.70/hr" },
      },
    },
    {
      name: "Gladstone Park Tennis",
      slug: "gladstone-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/GladstoneParkTennis/Booking/BookByDate",
      location: "Gladstone Park, Dollis Hill, London NW2",
      metadata: {
        lat: 51.559628, lng: -0.239670,
        venue: "GladstoneParkTennis",
        deepLink: "https://clubspark.lta.org.uk/GladstoneParkTennis/Booking/BookByDate",
        courts: 8, surface: "Macadam",
      },
    },
    {
      name: "Ravenscourt Park Tennis",
      slug: "ravenscourt-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/RavenscourtPark/Booking/BookByDate",
      location: "Ravenscourt Park, London W6",
      metadata: {
        lat: 51.494901, lng: -0.237160,
        venue: "RavenscourtPark",
        deepLink: "https://clubspark.lta.org.uk/RavenscourtPark/Booking/BookByDate",
        courts: 7, surface: "Tarmac",
      },
    },
    // === Greenwich ===
    {
      name: "Blackheath Tennis",
      slug: "blackheath",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BlackheathPark/Booking/BookByDate",
      location: "Chesterfield Walk, Blackheath, London SE10 8QX",
      metadata: {
        lat: 51.464715, lng: -0.002281,
        venue: "BlackheathPark",
        deepLink: "https://clubspark.lta.org.uk/BlackheathPark/Booking/BookByDate",
        courts: 3, surface: "Hard",
        pricing: { adult: "£6.30/hr", junior: "£4.20/hr" },
      },
    },
    {
      name: "Maryon Park Tennis",
      slug: "maryon-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/MaryonPark/Booking/BookByDate",
      location: "Maryon Park, Charlton, London SE7",
      metadata: {
        lat: 51.478901, lng: 0.027441,
        venue: "MaryonPark",
        deepLink: "https://clubspark.lta.org.uk/MaryonPark/Booking/BookByDate",
        pricing: { standard: "£3/hr" },
      },
    },
    {
      name: "Plumstead Common Tennis",
      slug: "plumstead-common",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/PlumsteadCommon/Booking/BookByDate",
      location: "Plumstead Common, London SE18",
      metadata: {
        lat: 51.480972, lng: 0.054303,
        venue: "PlumsteadCommon",
        deepLink: "https://clubspark.lta.org.uk/PlumsteadCommon/Booking/BookByDate",
        pricing: { standard: "£3/hr" },
      },
    },
    {
      name: "Kidbrooke Green Tennis",
      slug: "kidbrooke-green",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/KidbrookeGreen/Booking/BookByDate",
      location: "Kidbrooke Green, London SE9",
      metadata: {
        lat: 51.451504, lng: 0.037273,
        venue: "KidbrookeGreen",
        deepLink: "https://clubspark.lta.org.uk/KidbrookeGreen/Booking/BookByDate",
        pricing: { standard: "£3/hr" },
      },
    },
    {
      name: "Bostall Gardens Tennis",
      slug: "bostall-gardens",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BostallGardens/Booking/BookByDate",
      location: "Bostall Gardens, London SE2",
      metadata: {
        lat: 51.471816, lng: 0.072325,
        venue: "BostallGardens",
        deepLink: "https://clubspark.lta.org.uk/BostallGardens/Booking/BookByDate",
        pricing: { standard: "£3/hr" },
      },
    },
    {
      name: "Altash Gardens Tennis",
      slug: "altash-gardens",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/AltashGardens/Booking/BookByDate",
      location: "Altash Gardens, London SE9 3AL",
      metadata: {
        lat: 51.454633, lng: 0.067640,
        venue: "AltashGardens",
        deepLink: "https://clubspark.lta.org.uk/AltashGardens/Booking/BookByDate",
        pricing: { standard: "£3/hr" },
      },
    },
    // === Southwark ===
    {
      name: "Burgess Park Tennis",
      slug: "burgess-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BurgessParkSouthwark/Booking/BookByDate",
      location: "Burgess Park, London SE5 7LA",
      metadata: {
        lat: 51.493077, lng: -0.073038,
        venue: "BurgessParkSouthwark",
        deepLink: "https://clubspark.lta.org.uk/BurgessParkSouthwark/Booking/BookByDate",
        courts: 7, floodlit: true,
        pricing: { peak: "£9.40/hr", offPeak: "£6.80/hr" },
      },
    },
    {
      name: "Dulwich Park Tennis",
      slug: "dulwich-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/DulwichPark/Booking/BookByDate",
      location: "Dulwich Park, London SE21 7EB",
      metadata: {
        lat: 51.452727, lng: -0.081018,
        venue: "DulwichPark",
        deepLink: "https://clubspark.lta.org.uk/DulwichPark/Booking/BookByDate",
        courts: 4,
        pricing: { peak: "£9.40/hr", offPeak: "£6.80/hr" },
      },
    },
    {
      name: "Belair Park Tennis",
      slug: "belair-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BelairPark/Booking/BookByDate",
      location: "Belair Park, London SE21 7EX",
      metadata: {
        lat: 51.444272, lng: -0.087135,
        venue: "BelairPark",
        deepLink: "https://clubspark.lta.org.uk/BelairPark/Booking/BookByDate",
        pricing: { peak: "£9.40/hr", offPeak: "£6.80/hr" },
      },
    },
    {
      name: "Tanner Street Park Tennis",
      slug: "tanner-street-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/TannerStPark/Booking/BookByDate",
      location: "Tanner Street Park, Bermondsey, London SE1 3LL",
      metadata: {
        lat: 51.500012, lng: -0.080131,
        venue: "TannerStPark",
        deepLink: "https://clubspark.lta.org.uk/TannerStPark/Booking/BookByDate",
        pricing: { peak: "£9.40/hr", offPeak: "£6.80/hr" },
      },
    },
    {
      name: "Brunswick Park Tennis",
      slug: "brunswick-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BrunswickParkSouthwark/Booking/BookByDate",
      location: "Brunswick Park, London SE5 7RH",
      metadata: {
        lat: 51.475195, lng: -0.085515,
        venue: "BrunswickParkSouthwark",
        deepLink: "https://clubspark.lta.org.uk/BrunswickParkSouthwark/Booking/BookByDate",
        pricing: { peak: "£9.40/hr", offPeak: "£6.80/hr" },
      },
    },
    // === Lambeth ===
    {
      name: "Ruskin Park Tennis",
      slug: "ruskin-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/ruskinpark/Booking/BookByDate",
      location: "Ruskin Park, Denmark Hill, London SE5 8EL",
      metadata: {
        lat: 51.466403, lng: -0.094051,
        venue: "ruskinpark",
        deepLink: "https://clubspark.lta.org.uk/ruskinpark/Booking/BookByDate",
      },
    },
    {
      name: "Vauxhall Park Tennis",
      slug: "vauxhall-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/vauxhallpark/Booking/BookByDate",
      location: "Vauxhall Park, London SW8 1UD",
      metadata: {
        lat: 51.482551, lng: -0.122581,
        venue: "vauxhallpark",
        deepLink: "https://clubspark.lta.org.uk/vauxhallpark/Booking/BookByDate",
        courts: 2,
      },
    },
    {
      name: "Hillside Gardens Park Tennis",
      slug: "hillside-gardens-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/HillsideGardensPark/Booking/BookByDate",
      location: "Hillside Gardens Park, London SW2 3HL",
      metadata: {
        lat: 51.450940, lng: -0.108588,
        venue: "HillsideGardensPark",
        deepLink: "https://clubspark.lta.org.uk/HillsideGardensPark/Booking/BookByDate",
        courts: 4,
      },
    },
    // === East London ===
    {
      name: "West Ham Park Tennis",
      slug: "west-ham-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/westhampark/Booking/BookByDate",
      location: "West Ham Park, London E15",
      metadata: {
        lat: 51.537600, lng: 0.007189,
        venue: "westhampark",
        deepLink: "https://clubspark.lta.org.uk/westhampark/Booking/BookByDate",
        courts: 6, surface: "Hard",
        pricing: { standard: "£7.60/hr", concession: "£4.60/hr" },
      },
    },
    {
      name: "Honor Oak Recreation Ground Tennis",
      slug: "honor-oak",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/HonorOakRecreationGround/Booking/BookByDate",
      location: "Honor Oak Recreation Ground, London SE23 3LB",
      metadata: {
        lat: 51.452200, lng: -0.044522,
        venue: "HonorOakRecreationGround",
        deepLink: "https://clubspark.lta.org.uk/HonorOakRecreationGround/Booking/BookByDate",
        pricing: { peak: "£9.40/hr", offPeak: "£6.80/hr" },
      },
    },
    // === Royal Parks (Flow.onl) ===
    {
      name: "Hyde Park Tennis",
      slug: "hyde-park",
      bookingSystem: "flow_onl",
      bookingUrl: "https://sportsandleisureroyalparks.bookings.flow.onl/location/hyde-park-courts/tennis",
      location: "Hyde Park, South Carriage Drive, London W2 2UH",
      metadata: {
        lat: 51.503222, lng: -0.172189,
        venue: "hyde-park-courts",
        deepLink: "https://sportsandleisureroyalparks.bookings.flow.onl/location/hyde-park-courts/tennis",
        courts: 6, floodlit: true,
      },
    },
    {
      name: "Regent's Park Tennis",
      slug: "regents-park",
      bookingSystem: "flow_onl",
      bookingUrl: "https://sportsandleisureroyalparks.bookings.flow.onl/location/the-regents-park-courts/tennis",
      location: "The Regent's Park, York Bridge, London NW1 4NR",
      metadata: {
        lat: 51.525830, lng: -0.152566,
        venue: "the-regents-park-courts",
        deepLink: "https://sportsandleisureroyalparks.bookings.flow.onl/location/the-regents-park-courts/tennis",
        courts: 12, floodlit: true,
      },
    },
    {
      name: "Greenwich Park Tennis",
      slug: "greenwich-park",
      bookingSystem: "flow_onl",
      bookingUrl: "https://sportsandleisureroyalparks.bookings.flow.onl/location/greenwich-park-courts/tennis",
      location: "Greenwich Park, Blackheath Avenue, London SE10 8QY",
      metadata: {
        lat: 51.474517, lng: -0.001089,
        venue: "greenwich-park-courts",
        deepLink: "https://sportsandleisureroyalparks.bookings.flow.onl/location/greenwich-park-courts/tennis",
        courts: 6,
      },
    },
    // === East London — Tower Hamlets (near Canary Wharf) ===
    {
      name: "Victoria Park Tennis",
      slug: "victoria-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/VictoriaParkLONDON/Booking/BookByDate",
      location: "Victoria Park, London E9 5DU",
      metadata: {
        lat: 51.540360, lng: -0.033918,
        venue: "VictoriaParkLONDON",
        deepLink: "https://clubspark.lta.org.uk/VictoriaParkLONDON/Booking/BookByDate",
        courts: 4, surface: "Hard",
        pricing: { offPeak: "£4/hr", peak: "£6/hr" },
      },
    },
    {
      name: "Poplar Rec Ground Tennis",
      slug: "poplar-rec-ground",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/PoplarRecGround/Booking/BookByDate",
      location: "Poplar Recreation Ground, London E14 0BP",
      metadata: {
        lat: 51.510734, lng: -0.016257,
        venue: "PoplarRecGround",
        deepLink: "https://clubspark.lta.org.uk/PoplarRecGround/Booking/BookByDate",
        pricing: { offPeak: "£4/hr", peak: "£6/hr" },
      },
    },
    {
      name: "Ropemakers Fields Tennis",
      slug: "ropemakers-fields",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/RopemakersFields/Booking/BookByDate",
      location: "Ropemakers Fields, Limehouse, London E14 8BX",
      metadata: {
        lat: 51.509676, lng: -0.031879,
        venue: "RopemakersFields",
        deepLink: "https://clubspark.lta.org.uk/RopemakersFields/Booking/BookByDate",
        pricing: { offPeak: "£4/hr", peak: "£6/hr" },
      },
    },
    {
      name: "Wapping Gardens Tennis",
      slug: "wapping-gardens",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/WappingGardens/Booking/BookByDate",
      location: "Wapping Gardens, London E1 2QE",
      metadata: {
        lat: 51.504263, lng: -0.059901,
        venue: "WappingGardens",
        deepLink: "https://clubspark.lta.org.uk/WappingGardens/Booking/BookByDate",
        pricing: { offPeak: "£4/hr", peak: "£6/hr" },
      },
    },
    // === East London — Redbridge ===
    {
      name: "Valentines Park Tennis",
      slug: "valentines-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/ValentinesPark/Booking/BookByDate",
      location: "Valentines Park, Ilford IG1",
      metadata: {
        lat: 51.567730, lng: 0.085155,
        venue: "ValentinesPark",
        deepLink: "https://clubspark.lta.org.uk/ValentinesPark/Booking/BookByDate",
        pricing: { offPeak: "£3/hr", peak: "£6/hr" },
      },
    },
    {
      name: "Clayhall Park Tennis",
      slug: "clayhall-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/ClayhallPark/Booking/BookByDate",
      location: "Clayhall Park, Ilford IG5 0EB",
      metadata: {
        lat: 51.584284, lng: 0.057084,
        venue: "ClayhallPark",
        deepLink: "https://clubspark.lta.org.uk/ClayhallPark/Booking/BookByDate",
        pricing: { offPeak: "£3/hr", peak: "£6/hr" },
      },
    },
    {
      name: "Seven Kings Park Tennis",
      slug: "seven-kings-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/SevenKingsPark/Booking/BookByDate",
      location: "Seven Kings Park, Ilford IG3",
      metadata: {
        lat: 51.5620, lng: 0.0850,
        venue: "SevenKingsPark",
        deepLink: "https://clubspark.lta.org.uk/SevenKingsPark/Booking/BookByDate",
        pricing: { offPeak: "£3/hr", peak: "£6/hr" },
      },
    },
    {
      name: "Goodmayes Park Tennis",
      slug: "goodmayes-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/GoodmayesPark/Booking/BookByDate",
      location: "Goodmayes Park, Ilford IG3",
      metadata: {
        lat: 51.5580, lng: 0.1010,
        venue: "GoodmayesPark",
        deepLink: "https://clubspark.lta.org.uk/GoodmayesPark/Booking/BookByDate",
        pricing: { offPeak: "£3/hr", peak: "£6/hr" },
      },
    },
    {
      name: "Barkingside Recreation Ground Tennis",
      slug: "barkingside-rec",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BarkingsideRecreationGround/Booking/BookByDate",
      location: "Barkingside Recreation Ground, Ilford IG6 2PE",
      metadata: {
        lat: 51.588659, lng: 0.079622,
        venue: "BarkingsideRecreationGround",
        deepLink: "https://clubspark.lta.org.uk/BarkingsideRecreationGround/Booking/BookByDate",
        pricing: { offPeak: "£3/hr", peak: "£6/hr" },
      },
    },
    {
      name: "Ray Park Tennis",
      slug: "ray-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/RayPark/Booking/BookByDate",
      location: "Ray Park, Woodford Green IG7",
      metadata: {
        lat: 51.592456, lng: 0.060217,
        venue: "RayPark",
        deepLink: "https://clubspark.lta.org.uk/RayPark/Booking/BookByDate",
        pricing: { offPeak: "£3/hr", peak: "£6/hr" },
      },
    },
    // === East London — Barking & Dagenham ===
    {
      name: "Barking Park Tennis",
      slug: "barking-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BarkingPark/Booking/BookByDate",
      location: "Barking Park, Barking IG11",
      metadata: {
        lat: 51.545286, lng: 0.086596,
        venue: "BarkingPark",
        deepLink: "https://clubspark.lta.org.uk/BarkingPark/Booking/BookByDate",
      },
    },
    // === East London — Newham ===
    {
      name: "Roman Park Tennis",
      slug: "roman-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/RomanParkTennis/Booking/BookByDate",
      location: "Roman Park, Newham, London",
      metadata: {
        lat: 51.524231, lng: 0.014979,
        venue: "RomanParkTennis",
        deepLink: "https://clubspark.lta.org.uk/RomanParkTennis/Booking/BookByDate",
      },
    },
    // === East London — Havering ===
    {
      name: "Raphael Park Tennis",
      slug: "raphael-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/RaphaelPark/Booking/BookByDate",
      location: "Raphael Park, Romford RM2 5EB",
      metadata: {
        lat: 51.571685, lng: 0.199956,
        venue: "RaphaelPark",
        deepLink: "https://clubspark.lta.org.uk/RaphaelPark/Booking/BookByDate",
        courts: 12, surface: "Tarmac",
        pricing: { standard: "£6/hr", offPeak: "£4/hr (weekday 9am-12pm)" },
      },
    },
    // === NE London — Haringey ===
    {
      name: "Priory Park Tennis",
      slug: "priory-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/PrioryPark2/Booking/BookByDate",
      location: "Priory Park, London N8",
      metadata: {
        lat: 51.579788, lng: -0.112839,
        venue: "PrioryPark2",
        deepLink: "https://clubspark.lta.org.uk/PrioryPark2/Booking/BookByDate",
        courts: 4,
        pricing: { peak: "£6/hr", offPeak: "Free (Mon-Fri before 4pm)" },
      },
    },
    {
      name: "Downhills Park Tennis",
      slug: "downhills-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/downhillsparktennisclub/Booking/BookByDate",
      location: "Downhills Park, London N17 6PD",
      metadata: {
        lat: 51.589517, lng: -0.087423,
        venue: "downhillsparktennisclub",
        deepLink: "https://clubspark.lta.org.uk/downhillsparktennisclub/Booking/BookByDate",
        courts: 2,
        pricing: { peak: "£6/hr", offPeak: "Free (Mon-Fri before 4pm)" },
      },
    },
    {
      name: "Chestnuts Park Tennis",
      slug: "chestnuts-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/ChestnutsPark/Booking/BookByDate",
      location: "Chestnuts Park, London N15",
      metadata: {
        lat: 51.5780, lng: -0.0730,
        venue: "ChestnutsPark",
        deepLink: "https://clubspark.lta.org.uk/ChestnutsPark/Booking/BookByDate",
        pricing: { peak: "£6/hr", offPeak: "Free (Mon-Fri before 4pm)" },
      },
    },
    {
      name: "Markfield Park Tennis",
      slug: "markfield-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/MarkfieldPark/Booking/BookByDate",
      location: "Markfield Park, London N15",
      metadata: {
        lat: 51.5710, lng: -0.0650,
        venue: "MarkfieldPark",
        deepLink: "https://clubspark.lta.org.uk/MarkfieldPark/Booking/BookByDate",
        pricing: { peak: "£6/hr", offPeak: "Free (Mon-Fri before 4pm)" },
      },
    },
    // === East London — Redbridge (additional) ===
    {
      name: "Loxford Park Tennis",
      slug: "loxford-park",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/LoxfordPark/Booking/BookByDate",
      location: "Loxford Park, Ilford IG1",
      metadata: {
        lat: 51.548753, lng: 0.079406,
        venue: "LoxfordPark",
        deepLink: "https://clubspark.lta.org.uk/LoxfordPark/Booking/BookByDate",
        pricing: { offPeak: "£3/hr", peak: "£6/hr" },
      },
    },
    {
      name: "Barley Lane Rec Tennis",
      slug: "barley-lane-rec",
      bookingSystem: "clubspark",
      bookingUrl: "https://clubspark.lta.org.uk/BarleyLaneRecGround/Booking/BookByDate",
      location: "Barley Lane Recreation Ground, Ilford IG3",
      metadata: {
        lat: 51.5650, lng: 0.1000,
        venue: "BarleyLaneRecGround",
        deepLink: "https://clubspark.lta.org.uk/BarleyLaneRecGround/Booking/BookByDate",
        pricing: { offPeak: "£3/hr", peak: "£6/hr" },
      },
    },
  ];

  console.log("Seeding courts...");

  for (const court of courts) {
    const existing = await prisma.court.findUnique({ where: { slug: court.slug } });
    if (existing) {
      console.log(`  Skipping ${court.name} (already exists)`);
      continue;
    }
    await prisma.court.create({ data: court });
    console.log(`  Created ${court.name}`);
  }

  console.log("Done!");
  await prisma.$disconnect();
}

main().catch(console.error);
